### ISSUE TITLE
.header issues

### ISSUE THREAD

**Issue by eko24ive** [Qwebeck/homework3#2]
Your `.header` blocks is not properly centered.
Also size of your circle is too small and font weight is way too big:
![image](https://cloud.githubusercontent.com/assets/25591824/22869825/c2ef8d0e-f1aa-11e6-87a4-832fa7295685.png)

Here is design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22869830/c9d49178-f1aa-11e6-9305-f73f63c8eb47.png)

**Comment by Qwebeck** [comment]
Fixed

**Comment by eko24ive** [comment]
Centering issue is fixed, but I see another layout issue appeared, please work on it:
![image](https://cloud.githubusercontent.com/assets/25591824/22897116/29090964-f22b-11e6-92a6-8f062026313f.png)

**Comment by Qwebeck** [comment]
![image](https://cloud.githubusercontent.com/assets/21079319/22899922/9dce0904-f23d-11e6-86f5-f9e46e3c6ef2.png)
Look 
In my browser it looks normal so i dont know what i need to do

**Comment by eko24ive** [comment]
This issue is reproducable on devices with big screen width (e.g. 1920px) you can test it via emulation in Chrome devtools
Why are you using position value on `.block` and `.position` ?

**Comment by Qwebeck** [comment]
I use position for this elements because i don*t found another decision for right element position and think that right choise was position absolute for .main and relative position for other elements
But now i found correct way and change position on margins
So i think problem is fixed
I watch in emulation with big screen width and it looks correct

**Comment by Qwebeck** [comment]
Sorry
I dont see problem with margins between header and content when wrote previuos message 
So i try to do something with it and wrote when it problem will be fixed

**Comment by Qwebeck** [comment]
Fixed

**Comment by eko24ive** [comment]
Awesome, good job !
