### ISSUE TITLE
Content blocks issues

### ISSUE THREAD

**Issue by eko24ive** [Qwebeck/homework3#3]
Your `.content` blocks have several issues.
- There is no padding between text and image. 
- Image is too small.

![image](https://cloud.githubusercontent.com/assets/25591824/22869858/2b6e6256-f1ab-11e6-8336-344681c00014.png)

Here is design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22869863/327b2c64-f1ab-11e6-8219-7b4cc32a3c65.png)

**Comment by Qwebeck** [comment]
Fixed

**Comment by eko24ive** [comment]
Nicely done !
