### ISSUE TITLE
Missing horizontal line between content blocks

### ISSUE THREAD

**Issue by eko24ive** [Qwebeck/homework3#4]
Here is how your blocks looks without horizontal lines:
![image](https://cloud.githubusercontent.com/assets/25591824/22869996/4783315a-f1ac-11e6-95cc-d745b5167089.png)

## And this is how horizontal lines looks on design:

![image](https://cloud.githubusercontent.com/assets/25591824/22869563/c9a3bc58-f1a8-11e6-8bc3-56a4b9508f68.png)

**Comment by Qwebeck** [comment]
Fixed

**Comment by eko24ive** [comment]
I see that. Gorgeous !
